project:
  type: website

website:
  title: "Anna Zirkes - Geospatial Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.html
        text: Projects
      - href: contact.qmd
        text: Contact Me

format:
  html:
    theme:
      - darkly
      - brand
    css: assets/styles.css
    toc: false
    include-in-header:
      - text: |
          <script src="assets/main.js"></script>